### ISSUE TITLE
Results DF header should link to the port, instead of the asset

### ISSUE THREAD

**Issue by MichielTukker** [Project-OMOTES/simulator-core#114]
The header of the results dataframe currently doesn't differentiate between multiple in/out ports for a single asset,  it only differentiates between the inport ("_supply") and outports ("_return"). 

This is needed in simulator-worker  for the mapping of time series to ESDL asset ports

This blocks #108

**Comment by samvanderzwan** [comment]
For this to worker we need to refactor some stuff, since now we pass everything back with the asset id, and we do not store the port ids, so we need to start doing that.
And then we need to store the data separate for both ports so we can easily store them in the output DF.
We can also check if it is possible to immediately store the data into a dataframe which we append every time step
